### PR TITLE
Add implementation of Chinese Restaurant process

### PR DESCRIPTION
**Pull request by ocramz**

### CODE REVIEW

**Comment by ocramz** [comment]
I can't find my notes on the PY process and I'm not sure anymore its implementation is correct. However it was easy to adapt to the CRP

**Comment by jtobin** [comment]
Marco -- I'll take a look post-haste.  Also, FWIW I have some old R implementations of these things kicking around in [another repo](https://github.com/jtobin/bnp), which might be useful for validation/verification.  Similarly I'm not *100%* sure about their correctness, but I think they should be about right.

**Comment by ocramz** [comment]
@jtobin would you like me to figure out a distribution test for this process before merging? It's basically a straight copy from Griffiths, Ghahramani 2005 - Infinite Latent Feature Models and theIndian Buffet Process (https://cocosci.princeton.edu/tom/papers/ibptr.pdf)

**Comment by jtobin** [comment]
Marco -- sorry for the delay, I've just been busy.  LGTM!  I only tweaked a couple of (mostly stylistic) things. :+1: :+1:

**Pull request merged**
